name: app-insight-metrics

on: [push, pull_request]

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    environment: development
   
    steps:
      - name: Deploy
        run: |
          echo "Testing deployment info tracking - test"
          
  prod-deployment:
    runs-on: ubuntu-latest
    environment: Prod - Plan 
   
    steps:
      - name: Deploy
        run: |
          echo "Testing deployment info tracking - Prod - Plan "
        
