name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Test Run
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -la
      - uses: actions/checkout@v2
      - run: |
          ls -la
      - run: |
          cat README.md
